name: dream_music
description: 一款基于网易云音乐API创建的音乐项目.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bitsdojo_window: ^0.1.6
  dio: ^4.0.6
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  crypto: ^3.0.2
  flutter_easyloading: ^3.0.5
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  path_provider: ^2.0.11
  audioplayers: ^5.2.1
  easy_refresh: ^3.0.4+2
  url_launcher: ^6.1.6
  id3_codec: ^0.0.10
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/leftmenu/
    - assets/json/
    - assets/music/bgm.mp3
    # - assets/music/lenfen.mp3

  fonts:
    - family: DINAlternate
      fonts:
        - asset: assets/fonts/DIN-RegularAlternate-2.otf

